### PR TITLE
Improve syntax coloring by using the code from DLS

### PR DESCRIPTION
**Pull request by RUSshy**
This makes things much easier to theme

<details>
  <summary>Before</summary>

Code_2rFNHtJZdV

3rJ4vlZKiD
Code_evpfnDx0G0

  
</details>

<details>
  <summary>After</summary>

Code_vf349WCFNp

Code_1OHP95eSYD
Code_JF0o9RVQLK

</details>

### CODE REVIEW

**Comment by RUSshy** [comment]
I'm noob with npm and typescript, i cloned your repo but it couldn't compile, i had to make few fixes to Promise thing

**Comment by RUSshy** [comment]
Maybe we should work on providing an official theme (dark/light) for D, so it can be used as a base for theming?

**Comment by WebFreak001** [comment]
it looks like you completely replaced the syntax file with the DLS file, rather than extending the existing one.

The license of DLS is incompatible with code-d so we are not allowed to simply take code.

**Comment by RUSshy** [comment]
The vscode plugin of DLS is MIT licensed:  https://github.com/d-language-server/vscode-dlang/blob/master/LICENSE.txt

**Comment by WebFreak001** [comment]
oh right I only checked DLS, not the vscode plugin so that's a good point.

Then for a real review:
- swapping out the entire thing will fix some issues but cause other issues in other areas, it could confuse people. The changes should be limited to what you want to replace, that's also easier to review.
- when the PR is ready you should take out the .ts changes (they would be done separately and `tsc` or compilation aren't needed for grammar updates anyway)

**Comment by RUSshy** [comment]
Thanks for reviewing the code

I'll do that on a separate repo, i will try to make changes easier to review, one at a time

**Pull request closed without merging**
