### PR TITLE
clarification that DMC is required.

### PR DESCRIPTION
**Pull request by zigszigsdk**

### CODE REVIEW

**Comment by WebFreak001** [comment]
uhh I'm pretty sure it isn't required, just ldc on windows and on linux only dmd

**Comment by zigszigsdk** [comment]
DMC is part of DMD, but you're right that the alternatives should be mentioned as well.

**Comment by WebFreak001** [comment]
uh well dmc is the digital mars C compiler, but that part isn't needed here at all

**Comment by zigszigsdk** [comment]
Right, DMC, DMD, LDC or any other compiler. I should be clearer. but regardless, It has to be installed separately.

**Comment by WebFreak001** [comment]
uh I'm not sure about the installation process of dmd on windows right now and if it asks about DMC but on linux you don't need DMC at all

**Comment by zigszigsdk** [comment]
This is not the point i'm trying to make. I'm saying that there should be mention of the compiler being needed separately.

**Comment by zigszigsdk** [comment]
https://github.com/Pure-D/code-d/pull/154

**Pull request closed without merging**
