### PR TITLE
Add /** */ pairs to autoClosingPairs

### PR DESCRIPTION
**Pull request by Heromyth**
I'm developing a extension for VS Code, which is about comments for many language including D. I wan to share the same language configuration for D withe code-d.

### CODE REVIEW

**Comment by WebFreak001** [comment]
This kind of feature already exists for functions and is provided by serve-d with smarter things:
autocomplete empty line before function declaration
doc result

when you press auto complete before a function, you get the `///`, `/**` and `/++` entries which will generate a complete documentation boilerplate for you. Having this in autoClosingPairs could clash with that.

I have also now pushed some commits to the serve-d WIP branch to make this feature more obvious to use (and to fix it in the first place)

I think for this to be merged it would just need to add the addition and not change the complete file and formatting. But even then you should mention first what advantage that would have over the existing solution

**Comment by Heromyth** [comment]
Cool! How to enable this? I got nothing when inputing ///, /** or /++ before a function. I'm using code-d 0.20.2.

**Comment by WebFreak001** [comment]
in the current serve-d release there is a regression. The next release will have it fixed and included.

**Comment by BogdanOlar** [comment]
Yes! I was just looking into how I might get automatic function documenting code. Looking forward for the next release :)

**Comment by WebFreak001** [comment]
released

**Pull request closed without merging**
